const CONSTS = {
	HEADER_MAPNAME_SIZE: 260,
	HEADER_GAMEDIRECTORY_SIZE: 260,

	DIRECTORY_ENTRY_COUNT_MIN: 1,
	DIRECTORY_ENTRY_COUNT_MAX: 1024,
	DIRECTORY_ENTRY_DESCRIPTION_SIZE: 64,

	FRAME_CONSOLE_COMMAND_SIZE: 64,
	FRAME_SKYNAME_SIZE: 32,
	FRAME_SIZE_MIN: 12,
	FRAME_TYPE_MIN: 2,
	FRAME_TYPE_MAX: 9,
	FRAME_TYPE_DEMO_START: 2,
	FRAME_TYPE_CONSOLE_COMMAND: 3,
	FRAME_TYPE_CLIENT_DATA: 4,
	FRAME_TYPE_NEXT_SECTION: 5,
	FRAME_TYPE_EVENT: 6,
	FRAME_TYPE_WEAPON_ANIM: 7,
	FRAME_TYPE_SOUND: 8,
	FRAME_TYPE_DEMO_BUFFER: 9,
};

export default CONSTS;
